-- =============================================================================
-- identity_documents: RBAC (user_roles), Auth Hook y políticas Storage
-- Requisito: bucket "identity_documents" debe existir y estar en modo privado
-- (crear desde Dashboard o API si no existe).
-- =============================================================================

-- 1. Tabla de roles (recomendación Supabase para RBAC)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'app_role' AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public.app_role AS ENUM ('admin');
  END IF;
END
$$;

create table if not exists public.user_roles (
  id         bigint generated by default as identity primary key,
  user_id    uuid references auth.users on delete cascade not null,
  role       public.app_role not null,
  unique (user_id, role)
);

comment on table public.user_roles is 'Roles de aplicación (ej. admin del workspace Keysely).';

-- RLS en user_roles: solo supabase_auth_admin puede leer para el hook
alter table public.user_roles enable row level security;

create policy "Allow auth admin to read user roles"
  on public.user_roles
  as permissive
  for select
  to supabase_auth_admin
  using (true);

revoke all on public.user_roles from authenticated, anon, public;
grant all on public.user_roles to supabase_auth_admin;

-- 2. Auth Hook: inyectar user_role en el JWT
create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
as $$
declare
  claims jsonb;
  user_role public.app_role;
begin
  select role into user_role
  from public.user_roles
  where user_id = (event->>'user_id')::uuid
  limit 1;

  claims := event->'claims';

  if user_role is not null then
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
  else
    claims := jsonb_set(claims, '{user_role}', 'null'::jsonb);
  end if;

  event := jsonb_set(event, '{claims}', claims);
  return event;
end;
$$;

grant usage on schema public to supabase_auth_admin;

grant execute on function public.custom_access_token_hook to supabase_auth_admin;
revoke execute on function public.custom_access_token_hook from authenticated, anon, public;

-- 3. Políticas en storage.objects para el bucket identity_documents
-- INSERT: solo usuarios autenticados en su propia carpeta (user id como primer segmento)
create policy "identity_documents_insert_own_folder"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'identity_documents'
    and (storage.foldername(name))[1]::uuid = auth.uid()
  );

-- SELECT: dueño del objeto o admin (user_role en JWT)
create policy "identity_documents_select_owner_or_admin"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'identity_documents'
    and (
      auth.uid() = (owner_id::uuid)
      or (auth.jwt()->>'user_role') = 'admin'
    )
  );

-- UPDATE: dueño o admin (necesario para upsert)
create policy "identity_documents_update_owner_or_admin"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'identity_documents'
    and (
      auth.uid() = (owner_id::uuid)
      or (auth.jwt()->>'user_role') = 'admin'
    )
  );

-- DELETE: dueño o admin (opcional; permite borrar/reemplazar)
create policy "identity_documents_delete_owner_or_admin"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'identity_documents'
    and (
      auth.uid() = (owner_id::uuid)
      or (auth.jwt()->>'user_role') = 'admin'
    )
  );