-- Create Occupations Table
create table if not exists public.occupations (
  id bigint generated by default as identity primary key,
  occupation_name text not null unique
);

-- Seed Occupations Data
insert into public.occupations (occupation_name)
values
  ('Administrador'), ('Contador'), ('Abogado'), ('Desarrollador de Software'), ('Médico'), ('Enfermero'), ('Maestro'), ('Arquitecto'), ('Ingeniero Civil'), ('Diseñador Gráfico'),
  ('Mecánico'), ('Electricista'), ('Carpintero'), ('Plomero'), ('Cocinero'), ('Chofer'), ('Vendedor'), ('Mesero'), ('Estilista'), ('Psicólogo'),
  ('Consultor'), ('Asistente Administrativo'), ('Nutriólogo'), ('Odontólogo'), ('Veterinario'), ('Químico'), ('Biólogo'), ('Periodista'), ('Traductor'), ('Mercadólogo'),
  ('Economista'), ('Actuario'), ('Albañil'), ('Herrero'), ('Pintor'), ('Jardinero'), ('Sastre'), ('Panadero'), ('Carnicero'), ('Cajero'),
  ('Repartidor'), ('Vigilante'), ('Agricultor'), ('Ganadero'), ('Pescador'), ('Minero'), ('Obrero'), ('Estudiante'), ('Ama de casa'), ('Jubilado'),
  ('Desempleado'), ('Otro')
on conflict (occupation_name) do nothing;

-- Create Space Types Table
create table if not exists public.space_types (
  id bigint generated by default as identity primary key,
  space_name text not null unique,
  picture_url text
);

-- Seed Space Types Data
insert into public.space_types (space_name)
values
  ('Salón de eventos'),
  ('Consultorio dental'),
  ('Consultorio médico'),
  ('Oficina privada'),
  ('Sala de Juntas'),
  ('Estudio fotográfico'),
  ('Estudio de grabación'),
  ('Despacho'),
  ('Estudio de tatuaje'),
  ('Taller creativo'),
  ('Consultorio psicológico'),
  ('Aula'),
  ('Terraza'),
  ('Jardín'),
  ('Auditorio'),
  ('Bodega'),
  ('Espacio comercial')
on conflict (space_name) do nothing;

-- Create Identity Documents Table
create table if not exists public.identity_documents (
  id uuid default gen_random_uuid() primary key,
  identity_type text check (identity_type in ('ine', 'passport', 'professional_id')),
  attachments text[], -- Array of URLs
  is_verified boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Profiles Table
create table if not exists public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  first_name text not null,
  last_name text not null,
  occupation_id bigint references public.occupations(id),
  location jsonb not null default '{}'::jsonb, 
  -- Expected structure: {"address": {...}, "geolocation": {"latitude": ..., "longitude": ...}}
  space_type_preferences bigint[], -- Array of references to space_types(id)
  identity_document_id uuid references public.identity_documents(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.occupations enable row level security;
alter table public.space_types enable row level security;
alter table public.identity_documents enable row level security;
alter table public.profiles enable row level security;

-- Create Policies (Basic public read for catalogs, user specific for profiles)
create policy "Occupations are viewable by everyone" on public.occupations for select using (true);
create policy "Space types are viewable by everyone" on public.space_types for select using (true);

create policy "Users can view their own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can insert their own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update their own profile" on public.profiles for update using (auth.uid() = id);

create policy "Users can view their own identity documents" on public.identity_documents for select using (
  exists (select 1 from public.profiles where profiles.identity_document_id = identity_documents.id and profiles.id = auth.uid())
);
-- Allow inserting identity documents implicitly or explicitly (simplified for now)
create policy "Users can insert identity documents" on public.identity_documents for insert with check (true);

-- Function to handle new user signup (optional, if we want to auto-create empty profiles, but user req implies specific fields are required so maybe not auto-create on generic signup)
-- Leaving out handle_new_user trigger for now as First/Last name are required and might not be present in raw auth metadata yet.
